// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    [Migration("20260925020010_V001")]
    partial class V001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologica.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCita"));

                    b.Property<string>("EstadoCita")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("date")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("IdConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdCita");

                    b.HasIndex("IdConsultorio");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("IdPaciente");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Consultorio", b =>
                {
                    b.Property<int>("IdConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsultorio"));

                    b.Property<string>("EquipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("NumeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("Piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("IdConsultorio");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologica.DetalleCita", b =>
                {
                    b.Property<int>("IdDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleCita"));

                    b.Property<decimal>("CostoAplicado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDetalleCita");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdTratamiento");

                    b.ToTable("detallecita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("impuestos");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCita");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.HistorialMedico", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("EnfermedadesPrevias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdPaciente");

                    b.ToTable("historialesmedicos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdontologo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("RegistroMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("IdOdontologo");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPaciente");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologica.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReceta"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("IdReceta");

                    b.HasIndex("IdCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTratamiento"));

                    b.Property<decimal>("CostoBase")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("costo_base");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("NombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("IdTratamiento");

                    b.ToTable("tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Cita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Consultorio", "Consultorio")
                        .WithMany()
                        .HasForeignKey("IdConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontologica.Factura", b =>
                {
                    b.HasOne("ClinicaOdontologica.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontologica.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Odontologo", b =>
                {
                    b.HasOne("ClinicaOdontologica.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("ClinicaOdontologica.Receta", b =>
                {
                    b.HasOne("ClinicaOdontologica.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
